# Generated by Django 3.0.4 on 2020-11-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_college_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_info',
            name='college_email',
            field=models.EmailField(max_length=100),
        ),
    ]
