# Generated by Django 3.0.4 on 2021-01-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_college_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_info',
            name='college_pic',
            field=models.URLField(null=True),
        ),
    ]
