# Generated by Django 3.0.4 on 2021-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_college_info_college_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_pic',
            field=models.URLField(null=True),
        ),
    ]
