# Generated by Django 3.0.4 on 2021-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_remove_college_info_college_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_info',
            name='city',
            field=models.CharField(choices=[('Kanpur', 'Kanpur'), ('Lucknow', 'Lucknow')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='college_info',
            name='description',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='college_info',
            name='state',
            field=models.CharField(choices=[('Uttar Pradesh', 'Uttar Pradesh')], default=None, max_length=100, null=True),
        ),
    ]
