# Generated by Django 3.0.7 on 2020-08-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
