# Generated by Django 3.0.4 on 2020-08-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='know_us',
            field=models.CharField(default=None, max_length=100, verbose_name='How do you know about this website?'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('Bad', 'Bad'), ('Average', 'Average'), ('Excellent', 'Excellent')], default=None, max_length=100, verbose_name='How much do you want to rate our website'),
        ),
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=10, verbose_name='Do you recommend this website to your friends'),
        ),
        migrations.AddField(
            model_name='review',
            name='suggestion',
            field=models.TextField(default=None, max_length=1000, verbose_name='Give your suggestions about how we can make this website even more good'),
        ),
    ]
