# Generated by Django 3.0.7 on 2020-08-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200813_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='know_us',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='How do you know about this website?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommend',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=10, null=True, verbose_name='Do you recommend this website to your friends'),
        ),
    ]
