# Generated by Django 3.0.7 on 2020-08-14 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0005_auto_20200813_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seconday_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100, verbose_name='What is your subject of interest?')),
                ('college', models.CharField(blank=True, max_length=100, null=True, verbose_name='What is your dream college')),
                ('interest_college', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Are you going to your subject of interest type of college?')),
                ('if_college', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did you go to your dream college??')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
