# Generated by Django 3.0.7 on 2020-08-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_seconday_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seconday_model',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What is your dream college?'),
        ),
        migrations.AlterField(
            model_name='seconday_model',
            name='if_college',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did you go to your dream college?'),
        ),
    ]
