# Generated by Django 3.0.7 on 2020-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20200814_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='seconday_model',
            name='reason',
            field=models.TextField(default=None, max_length=1000, verbose_name="Can you give any reason why you didn't get your dream college or subject of type of interest college."),
        ),
    ]
