# Generated by Django 3.0.7 on 2020-08-14 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0009_graduate_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graduate_models',
            new_name='Graduate_model',
        ),
    ]
