# Generated by Django 3.0.4 on 2020-10-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20200814_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graduate_model',
        ),
    ]
